name = "Tensars"
uuid = "a62f5f21-4d3d-4b01-908c-09b44819bc86"
authors = ["Rodney Polkinghorne <thisrod@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensArrays = "70eefb7d-4b42-471c-acf6-aaa17e297c50"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
